# This create a tag whenever it detectes a new version in style.css
# Mostly based on: https://github.com/afragen/github-updater/wiki/User-Build-Processes
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
    # Execute change detection only on master branch
    'master':
      - step:
          #image: atlassian/default-image:2
          name: Run version change detection script
          script:
            - /bin/bash new-version-tag.sh
